#Buildfile to instruct Travis how to build this project.
language:
  javascript
install:
  - npm install
  - bower install

script:
  - gulp    #build the app
  - mocha   #test the app

after_success:
  - test $TRAVIS_BRANCH == "master" && bash deploy.sh #Deploy to github gh-pages using the deploy.sh file

env:
  global:
    - secure: "Y0BRPGfdOfG20whcRqlRQc5gLyxcjYeqLiViX4ErzP+aUiItvjfua6HSi4nURYKr9MPa8omBGL/+KvxvevVxWLBiAKHMopzvD93IyjaCk1i6m7Vw5/WH0RuF7DRVtKHfU9ImfX/7flgiAGXkve6IYPrJLcpa+awNv36sBuXsJcBta9ApYz5F5Ny1j57zlS1dp2WlQCC7lCzAc6HiJB7XHayY9mfwyXC38P8/zksVvPq2t+4xdsVCq030GAc+kugnimYVEDwmN9aWisnPwYOho4OeBsnSdiIEjZYleAYu+kqChXBzZqqwbZbV4Q0RjXJP0PNQzKF0u3deYWCXTrJsF2CqWKrfoA0J45R3V26hKUq7lODygKsAL5L0YULJJOW78w7GqT2dPaH/6n1Qz4rYm68BOX9+W5Bi5795EAO+NVoL0kOnNdWwKILvMWkDEQB7cHbw1YSUZvmnoTCyEY87dWm644dN720yOVz9Kc/pHcvcA6gwRDaJCSamByxeCaUzv0DvE4pCGX3+2GNQEZBnTyw5ENnuGmAwR6wknYOGL1+WRkaM4fZie+nFSnao2yWFV4mTp6pjq1w5cnmu5gJCp7kp8rXdPb7Cv8N2vhieP6deeb7a0npjeDn+ahllhkpDmhkQY1kUPYdd1P8Lnd95j1qsSVfjxRZbZ0vp48tsVkQ=" #this token is needed to deploy to gh pages. will need to be changed for other forks.
